#!/bin/bash

kafka_directory="/home/mpuchawski/snap/kafka_2.13-2.7.0"

flag=$1

run_zookeeper(){
	gnome-terminal --tab --working-directory=$kafka_directory -x sh -c "bin/zookeeper-server-start.sh config/zookeeper.properties; bash"
}

run_kafka_server(){
	gnome-terminal --tab --working-directory=$kafka_directory -x sh -c "bin/kafka-server-start.sh config/server.properties; bash"
}

if [[ -n "$flag" ]]; then
	if [[ "$flag" == "-z" ]]; then
		run_zookeeper
	elif [[ "$flag" == "-s" ]]; then
		run_kafka_server
	fi
else
	run_zookeeper
	sleep 2
	run_kafka_server	
fi




